// API-specific types for request/response payloads

export interface ApiError {
    message: string;
    code?: string;
    details?: Record<string, unknown>;
}

export interface PaginationParams {
    offset: number;
    limit: number;
}

export interface PaginatedResponse<T> {
    data: T[];
    count: number;
    hasMore: boolean;
}

export interface ApproveClaimPayload {
    claimId: string;
    warehouseAdminId: string;
    warehouseAdminName: string;
    approvedQuantities: Record<string, number>;
}

export interface DenyClaimPayload {
    claimId: string;
    warehouseAdminId: string;
    warehouseAdminName: string;
    reason: string;
}

export interface CreateUserProjectPayload {
    user_id: string;
    project_id: string;
}

export interface SupabaseError {
    message: string;
    details: string;
    hint: string;
    code: string;
}

// Product Vendor relation type
export interface ProductVendor {
    id: string;
    product_id: string;
    vendor_id: string;
    product_sku: string;
    cost_price: number;
    moq?: number;
    lead_time_days?: number;
    is_primary: boolean;
    created_at: string;
    vendor?: {
        id: string;
        name: string;
        contact_name?: string;
        contact_email?: string;
    };
    product?: {
        id: string;
        product_name: string;
        sku: string;
    };
}

// Create/Update payload types
export type CreateProjectPayload = {
    name: string;
    description?: string;
    location?: string;
    status: string;
    template_id?: string;
};

export type UpdateProjectPayload = Partial<CreateProjectPayload>;

export type CreateClaimPayload = {
    claim_number?: string; // Auto-generated by DB using generate_claim_number() → CLM-YYYY-####
    project_id: string;
    onsite_user_id: string;
    onsite_user_name: string;
    claim_type: 'standard' | 'emergency';
    emergency_reason?: string;
    photo_url?: string;
    notes?: string;
    claim_items?: Array<{
        product_id: string;
        quantity_requested: number;
    }>;
};

export type CreateReturnPayload = {
    project_id: string;
    claim_id: string;
    return_number: string;
    reason: string;
    notes?: string;
    return_items?: Array<{
        product_id: string;
        quantity: number;
    }>;
};

export type CreateStockAdjustmentPayload = {
    product_id: string;
    quantity_change: number;
    reason: string;
    notes?: string;
    admin_id: string;
    admin_name: string;
};

export type CreateNotificationPayload = {
    recipient_user_id?: string;
    recipient_role?: string;
    title: string;
    message: string;
    notification_type: string;
    related_entity_id?: string;
};

export type CreateTemplatePayload = {
    name: string;
    description?: string;
    is_active?: boolean;
};

export type UpdateTemplatePayload = Partial<CreateTemplatePayload>;

export type TemplateItemPayload = {
    product_id: string;
    phase: 'P1' | 'P2a' | 'P2b';
    required_quantity: number;
};

export type LinkProductToVendorPayload = {
    product_id: string;
    vendor_id: string;
    product_sku: string;
    cost_price: number;
    moq?: number;
    lead_time_days?: number;
    is_primary: boolean;
};

export type CreateAuditLogPayload = {
    action_type: string;
    user_id: string;
    user_name: string;
    details?: string;
    entity_type?: string;
    entity_id?: string;
};

export type CreateRequestPayload = {
    request_number: string;
    project_id?: string;
    requester_name: string;
    requester_email?: string;
    destination_property: string;
    created_by_role: string;
    photo_url?: string;
    request_items?: Array<{
        product_id: string;
        quantity_requested: number;
    }>;
};

export type CreatePurchaseOrderPayload = {
    po_number?: string; // Auto-generated by DB (SERIAL)
    vendor_id: string;
    order_date?: string | null;
    expected_delivery_date?: string | null;
    expected_delivery?: string | null; // DATE column in DB
    status?: string; // Defaults to 'draft' in DB
    total_amount?: number;
    notes?: string;
    created_by?: string | null;
    purchase_order_items?: Array<{
        product_id: string;
        quantity_ordered: number;
        unit_cost: number;
    }>;
};

export type UpdatePurchaseOrderPayload = Partial<Omit<CreatePurchaseOrderPayload, 'purchase_order_items'>>;

export type CreateProjectMaterialPayload = {
    project_id: string;
    product_id: string;
    quantity_allocated: number;
};

// Supabase query return type helper
export type SupabaseQueryReturn<T> = Promise<{
    data: T | null;
    error: SupabaseError | null;
}>;
